/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.46
 * Generated at: 2025-09-30 12:10:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<style>\r\n");
      out.write("    /* Reset */\r\n");
      out.write("    * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("        height: 100vh;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        background: linear-gradient(135deg, #0d1b2a, #1b263b, #415a77);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-container {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.05);\r\n");
      out.write("        backdrop-filter: blur(15px);\r\n");
      out.write("        padding: 45px 40px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        box-shadow: 0 15px 40px rgba(0,0,0,0.4);\r\n");
      out.write("        width: 350px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        border: 1px solid rgba(255,255,255,0.2);\r\n");
      out.write("        transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-container:hover {\r\n");
      out.write("        transform: translateY(-5px);\r\n");
      out.write("        box-shadow: 0 20px 50px rgba(0,0,0,0.6);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-container h2 {\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("        font-size: 28px;\r\n");
      out.write("        color: #f0e68c; /* subtle golden text */\r\n");
      out.write("        letter-spacing: 1px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-container input[type=\"text\"],\r\n");
      out.write("    .login-container input[type=\"password\"] {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 14px 15px;\r\n");
      out.write("        margin: 12px 0;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        transition: background 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-container input[type=\"text\"]::placeholder,\r\n");
      out.write("    .login-container input[type=\"password\"]::placeholder {\r\n");
      out.write("        color: #ddd;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-container input[type=\"text\"]:focus,\r\n");
      out.write("    .login-container input[type=\"password\"]:focus {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.25);\r\n");
      out.write("        box-shadow: 0 0 10px rgba(255, 255, 255, 0.5);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-container input[type=\"submit\"] {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 14px;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        background: linear-gradient(135deg, #f0e68c, #ffd700);\r\n");
      out.write("        color: #0d1b2a;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: transform 0.2s ease, box-shadow 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-container input[type=\"submit\"]:hover {\r\n");
      out.write("        transform: scale(1.05);\r\n");
      out.write("        box-shadow: 0 5px 20px rgba(255, 215, 0, 0.5);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-container p {\r\n");
      out.write("        margin-top: 15px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        color: #ddd;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-container a {\r\n");
      out.write("        color: #f0e68c;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-container a:hover {\r\n");
      out.write("        text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"login-container\">\r\n");
      out.write("        <h2>Welcome Back</h2>\r\n");
      out.write("        <form action=\"verifyLogin\" method=\"post\">\r\n");
      out.write("            <input type=\"text\" name=\"email\" placeholder=\"Enter your Email\" required />\r\n");
      out.write("            <input type=\"password\" name=\"password\" placeholder=\"Enter your Password\" required />\r\n");
      out.write("            <input type=\"submit\" value=\"Login\"/>\r\n");
      out.write("        </form>\r\n");
      out.write("        <p>Don’t have an account? <a href=\"register.jsp\">Register here</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

    if(request.getAttribute("error")!=null){
    out.println(request.getAttribute("error"));
    }
    
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
